/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PatientRouteRouteImport } from './routes/patient/route'
import { Route as DoctorRouteRouteImport } from './routes/doctor/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient/index'
import { Route as DoctorIndexRouteImport } from './routes/doctor/index'
import { Route as PCodeRouteImport } from './routes/p.$code'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authEnterOtpRouteImport } from './routes/(auth)/enter-otp'
import { Route as PatientProfileIndexRouteImport } from './routes/patient/profile/index'
import { Route as DoctorRxMemoryIndexRouteImport } from './routes/doctor/rx-memory/index'
import { Route as DoctorProfileIndexRouteImport } from './routes/doctor/profile/index'
import { Route as DoctorConsultationsIndexRouteImport } from './routes/doctor/consultations/index'
import { Route as PatientProfileEditRouteImport } from './routes/patient/profile/edit'
import { Route as PatientPrescriptionsPrescriptionIdRouteImport } from './routes/patient/prescriptions.$prescriptionId'
import { Route as DoctorPrescribeConsultationIdRouteImport } from './routes/doctor/prescribe.$consultationId'
import { Route as DoctorConsultationsPrescriptionIdRouteImport } from './routes/doctor/consultations/$prescriptionId'
import { Route as DoctorRxMemoryManageIndexRouteImport } from './routes/doctor/rx-memory/manage.index'
import { Route as DoctorRxMemoryManageTemplateIdRouteImport } from './routes/doctor/rx-memory/manage.$templateId'
import { Route as DoctorConsultationUserIdConsultationIdRouteImport } from './routes/doctor/consultation.$userId.$consultationId'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRouteRoute = PatientRouteRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRouteRoute = DoctorRouteRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRouteRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const PCodeRoute = PCodeRouteImport.update({
  id: '/p/$code',
  path: '/p/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authEnterOtpRoute = authEnterOtpRouteImport.update({
  id: '/enter-otp',
  path: '/enter-otp',
  getParentRoute: () => authRouteRoute,
} as any)
const PatientProfileIndexRoute = PatientProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => PatientRouteRoute,
} as any)
const DoctorRxMemoryIndexRoute = DoctorRxMemoryIndexRouteImport.update({
  id: '/rx-memory/',
  path: '/rx-memory/',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorProfileIndexRoute = DoctorProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorConsultationsIndexRoute =
  DoctorConsultationsIndexRouteImport.update({
    id: '/consultations/',
    path: '/consultations/',
    getParentRoute: () => DoctorRouteRoute,
  } as any)
const PatientProfileEditRoute = PatientProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientPrescriptionsPrescriptionIdRoute =
  PatientPrescriptionsPrescriptionIdRouteImport.update({
    id: '/prescriptions/$prescriptionId',
    path: '/prescriptions/$prescriptionId',
    getParentRoute: () => PatientRouteRoute,
  } as any)
const DoctorPrescribeConsultationIdRoute =
  DoctorPrescribeConsultationIdRouteImport.update({
    id: '/prescribe/$consultationId',
    path: '/prescribe/$consultationId',
    getParentRoute: () => DoctorRouteRoute,
  } as any)
const DoctorConsultationsPrescriptionIdRoute =
  DoctorConsultationsPrescriptionIdRouteImport.update({
    id: '/consultations/$prescriptionId',
    path: '/consultations/$prescriptionId',
    getParentRoute: () => DoctorRouteRoute,
  } as any)
const DoctorRxMemoryManageIndexRoute =
  DoctorRxMemoryManageIndexRouteImport.update({
    id: '/rx-memory/manage/',
    path: '/rx-memory/manage/',
    getParentRoute: () => DoctorRouteRoute,
  } as any)
const DoctorRxMemoryManageTemplateIdRoute =
  DoctorRxMemoryManageTemplateIdRouteImport.update({
    id: '/rx-memory/manage/$templateId',
    path: '/rx-memory/manage/$templateId',
    getParentRoute: () => DoctorRouteRoute,
  } as any)
const DoctorConsultationUserIdConsultationIdRoute =
  DoctorConsultationUserIdConsultationIdRouteImport.update({
    id: '/consultation/$userId/$consultationId',
    path: '/consultation/$userId/$consultationId',
    getParentRoute: () => DoctorRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRouteRouteWithChildren
  '/patient': typeof PatientRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/not-found': typeof NotFoundRoute
  '/enter-otp': typeof authEnterOtpRoute
  '/sign-in': typeof authSignInRoute
  '/p/$code': typeof PCodeRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/doctor/consultations/$prescriptionId': typeof DoctorConsultationsPrescriptionIdRoute
  '/doctor/prescribe/$consultationId': typeof DoctorPrescribeConsultationIdRoute
  '/patient/prescriptions/$prescriptionId': typeof PatientPrescriptionsPrescriptionIdRoute
  '/patient/profile/edit': typeof PatientProfileEditRoute
  '/doctor/consultations': typeof DoctorConsultationsIndexRoute
  '/doctor/profile': typeof DoctorProfileIndexRoute
  '/doctor/rx-memory': typeof DoctorRxMemoryIndexRoute
  '/patient/profile': typeof PatientProfileIndexRoute
  '/doctor/consultation/$userId/$consultationId': typeof DoctorConsultationUserIdConsultationIdRoute
  '/doctor/rx-memory/manage/$templateId': typeof DoctorRxMemoryManageTemplateIdRoute
  '/doctor/rx-memory/manage': typeof DoctorRxMemoryManageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/not-found': typeof NotFoundRoute
  '/enter-otp': typeof authEnterOtpRoute
  '/sign-in': typeof authSignInRoute
  '/p/$code': typeof PCodeRoute
  '/doctor': typeof DoctorIndexRoute
  '/patient': typeof PatientIndexRoute
  '/doctor/consultations/$prescriptionId': typeof DoctorConsultationsPrescriptionIdRoute
  '/doctor/prescribe/$consultationId': typeof DoctorPrescribeConsultationIdRoute
  '/patient/prescriptions/$prescriptionId': typeof PatientPrescriptionsPrescriptionIdRoute
  '/patient/profile/edit': typeof PatientProfileEditRoute
  '/doctor/consultations': typeof DoctorConsultationsIndexRoute
  '/doctor/profile': typeof DoctorProfileIndexRoute
  '/doctor/rx-memory': typeof DoctorRxMemoryIndexRoute
  '/patient/profile': typeof PatientProfileIndexRoute
  '/doctor/consultation/$userId/$consultationId': typeof DoctorConsultationUserIdConsultationIdRoute
  '/doctor/rx-memory/manage/$templateId': typeof DoctorRxMemoryManageTemplateIdRoute
  '/doctor/rx-memory/manage': typeof DoctorRxMemoryManageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/doctor': typeof DoctorRouteRouteWithChildren
  '/patient': typeof PatientRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/not-found': typeof NotFoundRoute
  '/(auth)/enter-otp': typeof authEnterOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/p/$code': typeof PCodeRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/doctor/consultations/$prescriptionId': typeof DoctorConsultationsPrescriptionIdRoute
  '/doctor/prescribe/$consultationId': typeof DoctorPrescribeConsultationIdRoute
  '/patient/prescriptions/$prescriptionId': typeof PatientPrescriptionsPrescriptionIdRoute
  '/patient/profile/edit': typeof PatientProfileEditRoute
  '/doctor/consultations/': typeof DoctorConsultationsIndexRoute
  '/doctor/profile/': typeof DoctorProfileIndexRoute
  '/doctor/rx-memory/': typeof DoctorRxMemoryIndexRoute
  '/patient/profile/': typeof PatientProfileIndexRoute
  '/doctor/consultation/$userId/$consultationId': typeof DoctorConsultationUserIdConsultationIdRoute
  '/doctor/rx-memory/manage/$templateId': typeof DoctorRxMemoryManageTemplateIdRoute
  '/doctor/rx-memory/manage/': typeof DoctorRxMemoryManageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/doctor'
    | '/patient'
    | '/about'
    | '/coming-soon'
    | '/not-found'
    | '/enter-otp'
    | '/sign-in'
    | '/p/$code'
    | '/doctor/'
    | '/patient/'
    | '/doctor/consultations/$prescriptionId'
    | '/doctor/prescribe/$consultationId'
    | '/patient/prescriptions/$prescriptionId'
    | '/patient/profile/edit'
    | '/doctor/consultations'
    | '/doctor/profile'
    | '/doctor/rx-memory'
    | '/patient/profile'
    | '/doctor/consultation/$userId/$consultationId'
    | '/doctor/rx-memory/manage/$templateId'
    | '/doctor/rx-memory/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/coming-soon'
    | '/not-found'
    | '/enter-otp'
    | '/sign-in'
    | '/p/$code'
    | '/doctor'
    | '/patient'
    | '/doctor/consultations/$prescriptionId'
    | '/doctor/prescribe/$consultationId'
    | '/patient/prescriptions/$prescriptionId'
    | '/patient/profile/edit'
    | '/doctor/consultations'
    | '/doctor/profile'
    | '/doctor/rx-memory'
    | '/patient/profile'
    | '/doctor/consultation/$userId/$consultationId'
    | '/doctor/rx-memory/manage/$templateId'
    | '/doctor/rx-memory/manage'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/doctor'
    | '/patient'
    | '/about'
    | '/coming-soon'
    | '/not-found'
    | '/(auth)/enter-otp'
    | '/(auth)/sign-in'
    | '/p/$code'
    | '/doctor/'
    | '/patient/'
    | '/doctor/consultations/$prescriptionId'
    | '/doctor/prescribe/$consultationId'
    | '/patient/prescriptions/$prescriptionId'
    | '/patient/profile/edit'
    | '/doctor/consultations/'
    | '/doctor/profile/'
    | '/doctor/rx-memory/'
    | '/patient/profile/'
    | '/doctor/consultation/$userId/$consultationId'
    | '/doctor/rx-memory/manage/$templateId'
    | '/doctor/rx-memory/manage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  DoctorRouteRoute: typeof DoctorRouteRouteWithChildren
  PatientRouteRoute: typeof PatientRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ComingSoonRoute: typeof ComingSoonRoute
  NotFoundRoute: typeof NotFoundRoute
  PCodeRoute: typeof PCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/p/$code': {
      id: '/p/$code'
      path: '/p/$code'
      fullPath: '/p/$code'
      preLoaderRoute: typeof PCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/enter-otp': {
      id: '/(auth)/enter-otp'
      path: '/enter-otp'
      fullPath: '/enter-otp'
      preLoaderRoute: typeof authEnterOtpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/patient/profile/': {
      id: '/patient/profile/'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileIndexRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/doctor/rx-memory/': {
      id: '/doctor/rx-memory/'
      path: '/rx-memory'
      fullPath: '/doctor/rx-memory'
      preLoaderRoute: typeof DoctorRxMemoryIndexRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/profile/': {
      id: '/doctor/profile/'
      path: '/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileIndexRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/consultations/': {
      id: '/doctor/consultations/'
      path: '/consultations'
      fullPath: '/doctor/consultations'
      preLoaderRoute: typeof DoctorConsultationsIndexRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/patient/profile/edit': {
      id: '/patient/profile/edit'
      path: '/profile/edit'
      fullPath: '/patient/profile/edit'
      preLoaderRoute: typeof PatientProfileEditRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/prescriptions/$prescriptionId': {
      id: '/patient/prescriptions/$prescriptionId'
      path: '/prescriptions/$prescriptionId'
      fullPath: '/patient/prescriptions/$prescriptionId'
      preLoaderRoute: typeof PatientPrescriptionsPrescriptionIdRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/doctor/prescribe/$consultationId': {
      id: '/doctor/prescribe/$consultationId'
      path: '/prescribe/$consultationId'
      fullPath: '/doctor/prescribe/$consultationId'
      preLoaderRoute: typeof DoctorPrescribeConsultationIdRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/consultations/$prescriptionId': {
      id: '/doctor/consultations/$prescriptionId'
      path: '/consultations/$prescriptionId'
      fullPath: '/doctor/consultations/$prescriptionId'
      preLoaderRoute: typeof DoctorConsultationsPrescriptionIdRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/rx-memory/manage/': {
      id: '/doctor/rx-memory/manage/'
      path: '/rx-memory/manage'
      fullPath: '/doctor/rx-memory/manage'
      preLoaderRoute: typeof DoctorRxMemoryManageIndexRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/rx-memory/manage/$templateId': {
      id: '/doctor/rx-memory/manage/$templateId'
      path: '/rx-memory/manage/$templateId'
      fullPath: '/doctor/rx-memory/manage/$templateId'
      preLoaderRoute: typeof DoctorRxMemoryManageTemplateIdRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/consultation/$userId/$consultationId': {
      id: '/doctor/consultation/$userId/$consultationId'
      path: '/consultation/$userId/$consultationId'
      fullPath: '/doctor/consultation/$userId/$consultationId'
      preLoaderRoute: typeof DoctorConsultationUserIdConsultationIdRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authEnterOtpRoute: typeof authEnterOtpRoute
  authSignInRoute: typeof authSignInRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authEnterOtpRoute: authEnterOtpRoute,
  authSignInRoute: authSignInRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface DoctorRouteRouteChildren {
  DoctorIndexRoute: typeof DoctorIndexRoute
  DoctorConsultationsPrescriptionIdRoute: typeof DoctorConsultationsPrescriptionIdRoute
  DoctorPrescribeConsultationIdRoute: typeof DoctorPrescribeConsultationIdRoute
  DoctorConsultationsIndexRoute: typeof DoctorConsultationsIndexRoute
  DoctorProfileIndexRoute: typeof DoctorProfileIndexRoute
  DoctorRxMemoryIndexRoute: typeof DoctorRxMemoryIndexRoute
  DoctorConsultationUserIdConsultationIdRoute: typeof DoctorConsultationUserIdConsultationIdRoute
  DoctorRxMemoryManageTemplateIdRoute: typeof DoctorRxMemoryManageTemplateIdRoute
  DoctorRxMemoryManageIndexRoute: typeof DoctorRxMemoryManageIndexRoute
}

const DoctorRouteRouteChildren: DoctorRouteRouteChildren = {
  DoctorIndexRoute: DoctorIndexRoute,
  DoctorConsultationsPrescriptionIdRoute:
    DoctorConsultationsPrescriptionIdRoute,
  DoctorPrescribeConsultationIdRoute: DoctorPrescribeConsultationIdRoute,
  DoctorConsultationsIndexRoute: DoctorConsultationsIndexRoute,
  DoctorProfileIndexRoute: DoctorProfileIndexRoute,
  DoctorRxMemoryIndexRoute: DoctorRxMemoryIndexRoute,
  DoctorConsultationUserIdConsultationIdRoute:
    DoctorConsultationUserIdConsultationIdRoute,
  DoctorRxMemoryManageTemplateIdRoute: DoctorRxMemoryManageTemplateIdRoute,
  DoctorRxMemoryManageIndexRoute: DoctorRxMemoryManageIndexRoute,
}

const DoctorRouteRouteWithChildren = DoctorRouteRoute._addFileChildren(
  DoctorRouteRouteChildren,
)

interface PatientRouteRouteChildren {
  PatientIndexRoute: typeof PatientIndexRoute
  PatientPrescriptionsPrescriptionIdRoute: typeof PatientPrescriptionsPrescriptionIdRoute
  PatientProfileEditRoute: typeof PatientProfileEditRoute
  PatientProfileIndexRoute: typeof PatientProfileIndexRoute
}

const PatientRouteRouteChildren: PatientRouteRouteChildren = {
  PatientIndexRoute: PatientIndexRoute,
  PatientPrescriptionsPrescriptionIdRoute:
    PatientPrescriptionsPrescriptionIdRoute,
  PatientProfileEditRoute: PatientProfileEditRoute,
  PatientProfileIndexRoute: PatientProfileIndexRoute,
}

const PatientRouteRouteWithChildren = PatientRouteRoute._addFileChildren(
  PatientRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  DoctorRouteRoute: DoctorRouteRouteWithChildren,
  PatientRouteRoute: PatientRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ComingSoonRoute: ComingSoonRoute,
  NotFoundRoute: NotFoundRoute,
  PCodeRoute: PCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
