/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authEnterOtpRouteImport } from './routes/(auth)/enter-otp'
import { Route as DashboardTemplatesIndexRouteImport } from './routes/dashboard/templates/index'
import { Route as DashboardProfileIndexRouteImport } from './routes/dashboard/profile/index'
import { Route as DashboardConsultationsIndexRouteImport } from './routes/dashboard/consultations/index'
import { Route as DashboardProfileEditRouteImport } from './routes/dashboard/profile/edit'
import { Route as DashboardPrescribeConsultationIdRouteImport } from './routes/dashboard/prescribe.$consultationId'
import { Route as DashboardConsultationsPrescriptionIdRouteImport } from './routes/dashboard/consultations/$prescriptionId'
import { Route as DashboardTemplatesManageIndexRouteImport } from './routes/dashboard/templates/manage.index'
import { Route as DashboardTemplatesManageTemplateIdRouteImport } from './routes/dashboard/templates/manage.$templateId'
import { Route as DashboardConsultationUserIdConsultationIdRouteImport } from './routes/dashboard/consultation.$userId.$consultationId'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authEnterOtpRoute = authEnterOtpRouteImport.update({
  id: '/enter-otp',
  path: '/enter-otp',
  getParentRoute: () => authRouteRoute,
} as any)
const DashboardTemplatesIndexRoute = DashboardTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileIndexRoute = DashboardProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardConsultationsIndexRoute =
  DashboardConsultationsIndexRouteImport.update({
    id: '/consultations/',
    path: '/consultations/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProfileEditRoute = DashboardProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPrescribeConsultationIdRoute =
  DashboardPrescribeConsultationIdRouteImport.update({
    id: '/prescribe/$consultationId',
    path: '/prescribe/$consultationId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardConsultationsPrescriptionIdRoute =
  DashboardConsultationsPrescriptionIdRouteImport.update({
    id: '/consultations/$prescriptionId',
    path: '/consultations/$prescriptionId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTemplatesManageIndexRoute =
  DashboardTemplatesManageIndexRouteImport.update({
    id: '/templates/manage/',
    path: '/templates/manage/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTemplatesManageTemplateIdRoute =
  DashboardTemplatesManageTemplateIdRouteImport.update({
    id: '/templates/manage/$templateId',
    path: '/templates/manage/$templateId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardConsultationUserIdConsultationIdRoute =
  DashboardConsultationUserIdConsultationIdRouteImport.update({
    id: '/consultation/$userId/$consultationId',
    path: '/consultation/$userId/$consultationId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/coming-soon': typeof ComingSoonRoute
  '/not-found': typeof NotFoundRoute
  '/enter-otp': typeof authEnterOtpRoute
  '/sign-in': typeof authSignInRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/consultations/$prescriptionId': typeof DashboardConsultationsPrescriptionIdRoute
  '/dashboard/prescribe/$consultationId': typeof DashboardPrescribeConsultationIdRoute
  '/dashboard/profile/edit': typeof DashboardProfileEditRoute
  '/dashboard/consultations': typeof DashboardConsultationsIndexRoute
  '/dashboard/profile': typeof DashboardProfileIndexRoute
  '/dashboard/templates': typeof DashboardTemplatesIndexRoute
  '/dashboard/consultation/$userId/$consultationId': typeof DashboardConsultationUserIdConsultationIdRoute
  '/dashboard/templates/manage/$templateId': typeof DashboardTemplatesManageTemplateIdRoute
  '/dashboard/templates/manage': typeof DashboardTemplatesManageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/not-found': typeof NotFoundRoute
  '/enter-otp': typeof authEnterOtpRoute
  '/sign-in': typeof authSignInRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/consultations/$prescriptionId': typeof DashboardConsultationsPrescriptionIdRoute
  '/dashboard/prescribe/$consultationId': typeof DashboardPrescribeConsultationIdRoute
  '/dashboard/profile/edit': typeof DashboardProfileEditRoute
  '/dashboard/consultations': typeof DashboardConsultationsIndexRoute
  '/dashboard/profile': typeof DashboardProfileIndexRoute
  '/dashboard/templates': typeof DashboardTemplatesIndexRoute
  '/dashboard/consultation/$userId/$consultationId': typeof DashboardConsultationUserIdConsultationIdRoute
  '/dashboard/templates/manage/$templateId': typeof DashboardTemplatesManageTemplateIdRoute
  '/dashboard/templates/manage': typeof DashboardTemplatesManageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/coming-soon': typeof ComingSoonRoute
  '/not-found': typeof NotFoundRoute
  '/(auth)/enter-otp': typeof authEnterOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/consultations/$prescriptionId': typeof DashboardConsultationsPrescriptionIdRoute
  '/dashboard/prescribe/$consultationId': typeof DashboardPrescribeConsultationIdRoute
  '/dashboard/profile/edit': typeof DashboardProfileEditRoute
  '/dashboard/consultations/': typeof DashboardConsultationsIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/templates/': typeof DashboardTemplatesIndexRoute
  '/dashboard/consultation/$userId/$consultationId': typeof DashboardConsultationUserIdConsultationIdRoute
  '/dashboard/templates/manage/$templateId': typeof DashboardTemplatesManageTemplateIdRoute
  '/dashboard/templates/manage/': typeof DashboardTemplatesManageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/coming-soon'
    | '/not-found'
    | '/enter-otp'
    | '/sign-in'
    | '/dashboard/'
    | '/dashboard/consultations/$prescriptionId'
    | '/dashboard/prescribe/$consultationId'
    | '/dashboard/profile/edit'
    | '/dashboard/consultations'
    | '/dashboard/profile'
    | '/dashboard/templates'
    | '/dashboard/consultation/$userId/$consultationId'
    | '/dashboard/templates/manage/$templateId'
    | '/dashboard/templates/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coming-soon'
    | '/not-found'
    | '/enter-otp'
    | '/sign-in'
    | '/dashboard'
    | '/dashboard/consultations/$prescriptionId'
    | '/dashboard/prescribe/$consultationId'
    | '/dashboard/profile/edit'
    | '/dashboard/consultations'
    | '/dashboard/profile'
    | '/dashboard/templates'
    | '/dashboard/consultation/$userId/$consultationId'
    | '/dashboard/templates/manage/$templateId'
    | '/dashboard/templates/manage'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/dashboard'
    | '/coming-soon'
    | '/not-found'
    | '/(auth)/enter-otp'
    | '/(auth)/sign-in'
    | '/dashboard/'
    | '/dashboard/consultations/$prescriptionId'
    | '/dashboard/prescribe/$consultationId'
    | '/dashboard/profile/edit'
    | '/dashboard/consultations/'
    | '/dashboard/profile/'
    | '/dashboard/templates/'
    | '/dashboard/consultation/$userId/$consultationId'
    | '/dashboard/templates/manage/$templateId'
    | '/dashboard/templates/manage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ComingSoonRoute: typeof ComingSoonRoute
  NotFoundRoute: typeof NotFoundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/enter-otp': {
      id: '/(auth)/enter-otp'
      path: '/enter-otp'
      fullPath: '/enter-otp'
      preLoaderRoute: typeof authEnterOtpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/dashboard/templates/': {
      id: '/dashboard/templates/'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile/': {
      id: '/dashboard/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/consultations/': {
      id: '/dashboard/consultations/'
      path: '/consultations'
      fullPath: '/dashboard/consultations'
      preLoaderRoute: typeof DashboardConsultationsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile/edit': {
      id: '/dashboard/profile/edit'
      path: '/profile/edit'
      fullPath: '/dashboard/profile/edit'
      preLoaderRoute: typeof DashboardProfileEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/prescribe/$consultationId': {
      id: '/dashboard/prescribe/$consultationId'
      path: '/prescribe/$consultationId'
      fullPath: '/dashboard/prescribe/$consultationId'
      preLoaderRoute: typeof DashboardPrescribeConsultationIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/consultations/$prescriptionId': {
      id: '/dashboard/consultations/$prescriptionId'
      path: '/consultations/$prescriptionId'
      fullPath: '/dashboard/consultations/$prescriptionId'
      preLoaderRoute: typeof DashboardConsultationsPrescriptionIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/templates/manage/': {
      id: '/dashboard/templates/manage/'
      path: '/templates/manage'
      fullPath: '/dashboard/templates/manage'
      preLoaderRoute: typeof DashboardTemplatesManageIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/templates/manage/$templateId': {
      id: '/dashboard/templates/manage/$templateId'
      path: '/templates/manage/$templateId'
      fullPath: '/dashboard/templates/manage/$templateId'
      preLoaderRoute: typeof DashboardTemplatesManageTemplateIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/consultation/$userId/$consultationId': {
      id: '/dashboard/consultation/$userId/$consultationId'
      path: '/consultation/$userId/$consultationId'
      fullPath: '/dashboard/consultation/$userId/$consultationId'
      preLoaderRoute: typeof DashboardConsultationUserIdConsultationIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authEnterOtpRoute: typeof authEnterOtpRoute
  authSignInRoute: typeof authSignInRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authEnterOtpRoute: authEnterOtpRoute,
  authSignInRoute: authSignInRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardConsultationsPrescriptionIdRoute: typeof DashboardConsultationsPrescriptionIdRoute
  DashboardPrescribeConsultationIdRoute: typeof DashboardPrescribeConsultationIdRoute
  DashboardProfileEditRoute: typeof DashboardProfileEditRoute
  DashboardConsultationsIndexRoute: typeof DashboardConsultationsIndexRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
  DashboardTemplatesIndexRoute: typeof DashboardTemplatesIndexRoute
  DashboardConsultationUserIdConsultationIdRoute: typeof DashboardConsultationUserIdConsultationIdRoute
  DashboardTemplatesManageTemplateIdRoute: typeof DashboardTemplatesManageTemplateIdRoute
  DashboardTemplatesManageIndexRoute: typeof DashboardTemplatesManageIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardConsultationsPrescriptionIdRoute:
    DashboardConsultationsPrescriptionIdRoute,
  DashboardPrescribeConsultationIdRoute: DashboardPrescribeConsultationIdRoute,
  DashboardProfileEditRoute: DashboardProfileEditRoute,
  DashboardConsultationsIndexRoute: DashboardConsultationsIndexRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
  DashboardTemplatesIndexRoute: DashboardTemplatesIndexRoute,
  DashboardConsultationUserIdConsultationIdRoute:
    DashboardConsultationUserIdConsultationIdRoute,
  DashboardTemplatesManageTemplateIdRoute:
    DashboardTemplatesManageTemplateIdRoute,
  DashboardTemplatesManageIndexRoute: DashboardTemplatesManageIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ComingSoonRoute: ComingSoonRoute,
  NotFoundRoute: NotFoundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
